Rodkin_Maxim_Task19/WebApp/Models/AwardViewModel.cs
using Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Models
{
    public class AwardViewModel
    {
        public int Id { get; set; }

        public string Title { get; set; }
        public string Description { get; set; }

        public bool Checked { get; set; }

        public static AwardViewModel GetViewModel(Award reward, List<Award> userRewards)
        {
            var model = new AwardViewModel();
            model.Id = reward.Id;
            model.Title = reward.Title;
            model.Description = reward.Description;
            if (userRewards!=null)
            {
                model.Checked = userRewards.Any(r => r.Id == reward.Id);
            }
           
            return model;
        }
    }
}

Rodkin_Maxim_Task19/WebApp/Models/UserViewModel.cs
using Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Models
{
    public class UserViewModel
    {
        public int Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public DateTime Birthdate { get; set; }

        public List<Award> Awards { get; set; }

        public List<AwardViewModel> AvailableAwards { get; set; }

        public User ToUser()
        {
            User user = new User(Id, FirstName, LastName, Birthdate);
            user.Awards = AvailableAwards
                    .Where(r => r.Checked == true)
                    .Select(r => new Award(r.Id)).ToList();
            return user;

        }


        public static UserViewModel GetViewModel(User user, List<Award> availableRewards)
        {
            var userModel = new UserViewModel();
            if (user!=null)
            {
                userModel.Id = user.Id;
                userModel.FirstName = user.FirstName;
                userModel.LastName = user.LastName;
                userModel.Birthdate = user.Birthdate;
                userModel.Awards = user.Awards;
                var rewards = new List<AwardViewModel>();
                foreach (var reward in availableRewards)
                {
                    rewards.Add(AwardViewModel.GetViewModel(reward, user.Awards));
                }
                userModel.AvailableAwards = rewards.ToList();
            }
            else
            {
                var rewards = new List<AwardViewModel>();
                foreach (var reward in availableRewards)
                {
                    rewards.Add(AwardViewModel.GetViewModel(reward, null));
                }
                userModel.AvailableAwards = rewards.ToList();
            }
          
           
            return userModel;
        }

    }
}

Rodkin_Maxim_Task19/WebApp/Controllers/AwardController.cs
using Department.BLL;
using Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class AwardController: Controller
    {
        private static AwardBL awards = new AwardBL();

        static AwardController()
        {
            awards.InitList();
        }
        //
        // GET: /Award/

        public ActionResult Index()
        {
            ViewBag.HeaderText = "Awards list";
            return View(awards.GetList());
        }

        //
        // GET: /Award/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Award/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                awards.Add(new Award(collection["Title"], collection["Description"]));

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Award/Edit/5

        public ActionResult Edit(int id)
        {
            var currentAward = awards.GetList().FirstOrDefault(u => u.Id == id);
            return View(currentAward);
        }

        //
        // POST: /Award/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                awards.Edit(new Award(int.Parse(collection["Id"]), collection["Title"], collection["Description"]));
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Award/Delete/5

        public ActionResult Delete(int id)
        {
            var currentAward = awards.GetList().FirstOrDefault(u => u.Id == id);
            if (currentAward != null)
            {
                awards.Remove(currentAward);
            }

            return RedirectToAction("Index");
        }

      
        
    }
}

Rodkin_Maxim_Task19/WebApp/Controllers/UsersController.cs
using Department.BLL;
using Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class UsersController : Controller
    {
        private static UserBL users = new UserBL();
        private static AwardBL awards = new AwardBL();
        static UsersController()
        {
            users.InitList();
        }

        //
        // GET: /Users/

        public ActionResult Index()
        {
            ViewBag.HeaderText = "Users list";
            return View(users.GetList());
        }


        //
        // GET: /users/Create

        public ActionResult Create()
        {

            return View(UserViewModel.GetViewModel((new User() { firstName = "", lastName = "", birthdate = DateTime.Parse("01.01.01") }), awards.GetList()));
        }

        //
        // POST: /users/Create

        [HttpPost]
        public ActionResult Create(UserViewModel userModel)
        {
            try
            {
                users.Add(userModel.ToUser());

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /users/Edit/5

        public ActionResult Edit(int id)
        {
            //var currentUser = users.GetList().FirstOrDefault(u => u.Id == id);
            //return View(currentUser);
            var currentUser = users.GetList().FirstOrDefault(u => u.Id == id);
            return View(UserViewModel.GetViewModel(currentUser, awards.GetList()));
        }

        //
        // POST: /users/Edit/5

        [HttpPost]
        public ActionResult Edit(UserViewModel userModel)
        {
            try
            {
                
                    var userList = users.GetList();
                
                    var currentUser = userList.FirstOrDefault(u => u.Id == userModel.Id);
                    if (currentUser != null)
                    {
                        var user = userModel.ToUser();
                        currentUser.FirstName = user.FirstName;
                        currentUser.LastName = user.LastName;
                        currentUser.Birthdate = user.Birthdate;
                        currentUser.Awards = user.Awards;
                        users.Edit(user);
                    }
                
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        //
        // GET: /users/Delete/5

        public ActionResult Delete(int id)
        {
            var currentUser = users.GetList().FirstOrDefault(u => u.Id == id);
            if (currentUser != null)
            {
                users.Remove(currentUser);
            }
            return RedirectToAction("Index");
        }


    }
}

Rodkin_Maxim_Task19/WebApp/Views/Award/Create.cshtml
@model Entities.Award

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Award</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Rodkin_Maxim_Task19/WebApp/Views/Award/Edit.cshtml
@model Entities.Award

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Award</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Rodkin_Maxim_Task19/WebApp/Views/Award/Index.cshtml
@model IEnumerable<Entities.Award>

@{
    ViewBag.Title = "Awards list";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Rodkin_Maxim_Task19/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Users and Awards", "Index", "Users", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Users", "Index", "Users")</li>
                    <li>@Html.ActionLink("Awards", "Index", "Award")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Rodkin_Maxim_Task19/WebApp/Views/Users/Cre.cshtml
@model Entities.User

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>User</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Birthdate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Birthdate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            @using Department.BLL
            @{
        AwardBL award = new AwardBL();
        var awards = award.GetList();
        for (int i = 0; i < awards.Count; i++)
        {
            var r = awards[i];
            <label>@r.Title</label>
            <input type="number" name="awards[@i].Id" style="display: none;" value="@r.Id" />
            @Html.EditorFor(m=>awards[@i].Checked)

            <br />
}
            }
        </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Rodkin_Maxim_Task19/WebApp/Views/Users/Create.cshtml
@using WebApp.Models;
@model WebApp.Models.UserViewModel

@{
    ViewBag.Title = "Create";
}
@{
    ViewBag.Title = "Index";
    var currentUser = Model;

        currentUser = new UserViewModel();
 
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-horizontal">
        <h4>UserViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthdate, "", new { @class = "text-danger" })
            </div>
        </div>

        @{
            <div class="form-group">
                <p>Rewards</p>
                @{if (Model.AvailableAwards != null)
                    {
                        for (var i = 0; i < Model.AvailableAwards.Count; i++)
                        {
                            var r = Model.AvailableAwards[i];
                            <label>@r.Title</label>
                            <input type="number" name="AvailableAwards[@i].Id" style="display: none;" value="@r.Id" />
                            @Html.EditorFor(m => m.AvailableAwards[i].Checked)
                            // @Html.CheckBox($"AvailableAwards[{i}].Id", r.Checked)
                            <br />
                        }
                    }
                }
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Rodkin_Maxim_Task19/WebApp/Views/Users/Edit.cshtml
@model WebApp.Models.UserViewModel

@{
    ViewBag.Title = "Edit";
}


<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>UserViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthdate, "", new { @class = "text-danger" })
            </div>
        </div>

        @{
            <div class="form-group">
                <p>Rewards</p>
                @{if (Model.AvailableAwards != null)
                    {
                        for (var i = 0; i < Model.AvailableAwards.Count; i++)
                        {
                            var r = Model.AvailableAwards[i];
                            <label>@r.Title</label>
                            <input type="number" name="AvailableAwards[@i].Id" style="display: none;" value="@r.Id" />
                            @Html.EditorFor(m => m.AvailableAwards[i].Checked)
                            // @Html.CheckBox($"AvailableAwards[{i}].Id", r.Checked)
                            <br />
                        }
                    }
                }
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Rodkin_Maxim_Task19/WebApp/Views/Users/Index.cshtml
@model IEnumerable<Entities.User>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthdate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AwardsStr)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Birthdate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AwardsStr)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>